### ISSUE TITLE
担当者決定

### ISSUE THREAD

**Issue by alpha7Design** [alpha7Design/alice-web#1]
デザイン担当者を決定します。
---
#alpha

**Comment by hoshinokoe2338** [comment]
素材についてはこちらで集めます。

**Comment by alpha7Design** [comment]
クローズされてますがコメント追加。
こちらの写真を表紙で利用したい。
![img_1314](https://user-images.githubusercontent.com/38967842/39619814-0bc00cb6-4fc4-11e8-8751-9c1880594c42.jpg)
#2
#3

**Comment by hoshinokoe2338** [comment]
![300px-identicon svg](https://user-images.githubusercontent.com/10356500/39620080-e6523692-4fc4-11e8-9514-e9b00e5a8d0e.png)
